language: ruby
cache: bundler
sudo: false
rvm:
- 2.2
- 2.3.0
- 2.4.0
- 2.5.0
notifications:
  email:
    on_success: change
    on_failure: always
script:
- bundle exec rubocop
- bundle exec rspec spec
